### ISSUE TITLE
Need a mail markup.

### ISSUE THREAD

**Issue by b1gb4dw0lf** [anonrig/slack-manager#9]

**Comment by anonrig** [comment]
Options that I can think of:
- ~~Render mail templates using Jade in server-side.~~
- Use [email-templates](https://www.npmjs.com/package/email-templates) npm plugin (?). It also uses a templating engine like Jade etc. to render emails from Jade to HTML and to Email body.

**Comment by b1gb4dw0lf** [comment]
Mail markup can be improved. Questions and answers may be grouped, a colorful background might add joy to the mail. Different container style for users might look better for example the github commenting style like in this page.
